### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by CKGrafico**
Add payload in usestore

### CODE REVIEW

**Comment by CKGrafico** [comment]
Wait for more updates, I don't understand why payload are not in the overloads, doublechecking....

**Comment by CKGrafico** [comment]
Diff: https://www.diffchecker.com/g5LfDjGi

**Comment by CKGrafico** [comment]
Diff after update: https://www.diffchecker.com/FmgJsbEo
@jhonnymichel I hope this is the last.. not understand why the overloads were not at the PR

**Comment by jhonnymichel** [comment]
Thank you for continuously checking and supporting this!

Now that I understand types a little better I can double check as well, and I think there's nothing else to add. I'll release a version later today. Unless you tell me you really need a patch now so I can treat it with more urgency!

**Comment by CKGrafico** [comment]
I've change my `package.json` to use your master
```
    "react-hookstore": "github:jhonnymichel/react-hookstore",
```

looks great :D

Sorry for the extra work!

**Pull request merged**
