### PR TITLE
added setState callback

### PR DESCRIPTION
**Pull request by medyll**
added example to demo and readme

### CODE REVIEW

**Comment by jhonnymichel** [comment]
@Mydde It looks good to me. could you add tests before I merge this?

**Comment by jhonnymichel** [comment]
The project coverage is currently 100%, we should try to keep this rate

**Comment by jhonnymichel** [comment]
@Mydde I had updated master fixing tests for React 16.8. Could you rebase your branch?

If you find this + creating a test for you callback too much trouble just let me know and I can merge your PR and provide the changes needed myself. Thanks!

**Comment by medyll** [comment]
that's done
is it now that i have to write my 'first ever react tests' ? will have a look tonight, yes

**Comment by jhonnymichel** [comment]
Thank's, @Mydde. Your pull request will now be merged!

**Pull request merged**
